### ISSUE TITLE
Photo capture appears to get squeezed and framing. (before Previewing)

### ISSUE THREAD

**Issue by jpscigliano** [commonsguy/cwac-camera#285] opened 2015-06-16 15:00 UTC
When take a picture  the photo capture appears to get squeezed and framing. (before Previewing)

Test it on       HTC one X.  Android 4.1.1

Link to video. https://youtu.be/uUyTtH000pE

**Comment by commonsguy** [comment] 2015-06-16 15:02
Duplicate of issue #71

**Closed by commonsguy** 2015-06-16 15:02 UTC
