### ISSUE TITLE
Android Studio:Failed to find Dependency

### ISSUE THREAD

**Issue by meher421** [commonsguy/cwac-camera#248] opened 2015-01-03 16:08 UTC
I am trying to use this library in Android Studio and trying to add gradle in gradle dependencies as

compile 'com.commonsware.cwac:camera:0.6.+'

But Android studio throws error " Failed to find : com.commonsware.cwac:camera:0.6.+".

Please fix it as soon as possible.

**Comment by commonsguy** [comment] 2015-01-03 16:09
Closing as duplicate of issue #247

**Closed by commonsguy** 2015-01-03 16:09 UTC
