### ISSUE TITLE
Samsung S3 picture in top-right corner

### ISSUE THREAD

**Issue by BrutalCSkakan** [commonsguy/cwac-camera#256] opened 2015-02-12 09:50 UTC
Getting this strange error, seems to be only on the S3. 

https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpa1/v/t34.0-12/10968252_10152670195563359_2137140773_n.jpg?oh=8ff731e365f3eaae18f573ad40bfe256&oe=54DE0C20&__gda__=1423835405_2f3e42d0c6799cef17e85463ada8c12f

**Comment by commonsguy** [comment] 2015-02-12 12:17
This is a duplicate of issue #92. If you comment on that issue with what *specific* S3 you have (e.g., `Build.PRODUCT` value) and whether you are getting this with the demo app, it may help me eventually find a fix.

**Closed by commonsguy** 2015-02-12 12:17 UTC
